name: spot
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: node /app
    working_dir: /app
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - ./config:/app/config
    stop_grace_period: 1s
