name: spot
services:
    web:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        command: node /app
        working_dir: /app
        ports:
          - "8081:8080"
        